#!/bin/bash

echo 'Setting up CMSSW_10_2_23...'

source /cvmfs/cms.cern.ch/cmsset_default.sh
source /cvmfs/cms.cern.ch/crab3/crab.sh

scramv1 project CMSSW CMSSW_10_2_23
cd CMSSW_10_2_23/src
eval `scramv1 runtime -sh`

git clone git@github.com:msessini/EGammaAnalysisTools.git EGamma/EGammaAnalysisTools

git clone git@github.com:msessini/RecoilCorrections.git HTT-utilities/RecoilCorrections

git clone --recurse-submodules git@github.com:msessini/HiggsCPinTauDecays.git

git clone --branch run2_MuTau --single-branch git@github.com:msessini/LLRHiggsTauTau.git

git clone git@github.com:msessini/GeneratorInterface.git

git clone git@github.com:msessini/OldGEF TauPolSoftware/SimpleFits

git clone git@github.com:msessini/MuonAnalysisTools.git Muon/MuonAnalysisTools

git clone git@github.com:msessini/RecoEgamma.git

git clone git@github.com:msessini/RecoJets.git

git clone git@github.com:msessini/RecoMET.git

git clone git@github.com:msessini/RecoTauTag.git

git clone git@github.com:msessini/TauTriggerSFs.git TauAnalysisTools/TauTriggerSFs

git clone git@github.com:msessini/ClassicSVfit.git TauAnalysis/ClassicSVfit
git clone git@github.com:msessini/SVfitTF.git TauAnalysis/SVfitTF

git clone git@github.com:msessini/TauIDSFs.git TauPOG/TauIDSFs

git clone git@github.com:msessini/UFHZZAnalysisRun2.git

scramv1 b -j 8
