#!/bin/bash

echo 'Setting up CMSSW_10_2_23...'

source /cvmfs/cms.cern.ch/cmsset_default.sh
source /cvmfs/cms.cern.ch/crab3/crab.sh

scramv1 project CMSSW CMSSW_10_2_23
cd CMSSW_10_2_23/src
eval `scramv1 runtime -sh`

mkdir EGamma
cd EGamma
git clone git@github.com:msessini/EGammaAnalysisTools.git
cd $CMSSW_BASE/src

mkdir HTT-utilities
cd HTT-utilities
git clone git@github.com:msessini/RecoilCorrections.git
cd $CMSSW_BASE/src

git clone git@github.com:msessini/HiggsCPinTauDecays.git

git clone --branch TauTau --single-branch git@github.com:msessini/LLRHiggsTauTau.git

mkdir Muon
cd Muon
git clone git@github.com:msessini/MuonAnalysisTools.git
cd $CMSSW_BASE/src

git clone git@github.com:msessini/RecoEgamma.git

git clone git@github.com:msessini/RecoJets.git

git clone git@github.com:msessini/RecoMET.git

git clone git@github.com:msessini/RecoTauTag.git

mkdir TauAnalysisTools
cd TauAnalysisTools
git clone git@github.com:msessini/TauTriggerSFs.git
cd $CMSSW_BASE/src

mkdir TauAnalysis
cd TauAnalysis
git clone git@github.com:msessini/ClassicSVfit.git
git clone git@github.com:msessini/SVfitTF.git
cd $CMSSW_BASE/src

mkdir TauPOG
cd TauPOG
git clone git@github.com:msessini/TauIDSFs.git
cd $CMSSW_BASE/src

git clone git@github.com:msessini/UFHZZAnalysisRun2.git

scramv1 b -j 8
